@define-color blur_background8 alpha(rgba(0, 0, 0, 1), 0.8);
    @define-color primary #e2b778;
    @define-color primary_container #684b1e;
    @define-color primary_fixed #fad9ac;
    @define-color primary_fixed_dim #e2b778;
