cursor #a57c44
cursor_text_color #292d0d

foreground            #e5b67b
background            #100900
selection_foreground  #a57c44
selection_background  #d4bb9e
url_color             #e5b67b

color0 #100900
color1 #7e8650
color2 #583c16
color3 #e5b67b
color4 #a37c48
color5 #3e2907
color6 #a57c44
color7 #bac385
color8 #61503b
color9 #e5b67b
color10 #e6ded6
color11 #ccbeaf
color12 #a57c44
color13 #292d0d
color14 #ccbeaf
color15 #e5b67b
