
$background = rgba(000000ff)

$error = rgba(f8afa6ff)

$error_container = rgba(9d1b19ff)

$inverse_on_surface = rgba(1d1b18ff)

$inverse_primary = rgba(583c16ff)

$inverse_surface = rgba(e6ded6ff)

$on_background = rgba(e6ded6ff)

$on_error = rgba(160000ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(100900ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(3e2907ff)

$on_secondary = rgba(130d06ff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(3b2f1fff)

$on_surface = rgba(ece2dbff)

$on_surface_variant = rgba(ccbeafff)

$on_tertiary = rgba(050600ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(292d0dff)

$outline = rgba(95897cff)

$outline_variant = rgba(5c5348ff)

$primary = rgba(e5b67bff)

$primary_container = rgba(a37c48ff)

$primary_fixed = rgba(fad9b2ff)

$primary_fixed_dim = rgba(e5b67bff)

$scrim = rgba(000000ff)

$secondary = rgba(d4bb9eff)

$secondary_container = rgba(61503bff)

$secondary_fixed = rgba(f5dabcff)

$secondary_fixed_dim = rgba(d4bb9eff)

$shadow = rgba(000000ff)

$source_color = rgba(a57c44ff)

$surface = rgba(000000ff)

$surface_bright = rgba(2d2926ff)

$surface_container = rgba(0d0b0aff)

$surface_container_high = rgba(191715ff)

$surface_container_highest = rgba(26231fff)

$surface_container_low = rgba(050404ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(000000ff)

$surface_tint = rgba(e5b67bff)

$surface_variant = rgba(39322aff)

$tertiary = rgba(bac385ff)

$tertiary_container = rgba(7e8650ff)

$tertiary_fixed = rgba(dae2a1ff)

$tertiary_fixed_dim = rgba(bac385ff)
