general {
    # Pause all players and avoid starting multiple candylock instances
    lock_cmd = playerctl --all-players pause && pidof qs || qs -c candylock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 40                                                        # ~40s dim
    on-timeout = { brightnessctl -s && brightnessctl s 60% ;}          # dim monitor; avoid 0 on OLED
    on-resume = brightnessctl -r                                        # restore brightness
}

# Uncomment if you have keyboard backlight
# listener {
#     timeout = 480
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
#     on-resume = brightnessctl -rd rgb:kbd_backlight
# }

listener {
    timeout = 60                                                        # 1min
    on-timeout = loginctl lock-session                                  # triggers lock_cmd above
}

listener {
    timeout = 85                                                        # ~1m25s
    on-timeout = hyprctl dispatch dpms off                              # screen off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r            # screen on + brightness restore
}

listener {
    timeout = 90                                                        # 1m30s
    on-timeout = systemctl suspend                                      # suspend
}
